# Generated by Django 3.2.6 on 2021-10-04 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditureitem',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='incomeitem',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
