# Generated by Django 3.2.8 on 2021-10-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211004_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditureitem',
            name='category',
            field=models.CharField(choices=[('Entertainment', 'Entertainment'), ('Fooding', 'Fooding'), ('Housing', 'Housing'), ('Insurance', 'Insurance'), ('Insurance', 'Insurance'), ('Insurance', 'Insurance'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incomeitem',
            name='category',
            field=models.CharField(choices=[('Salary', 'Salary'), ('Freelance', 'Freelance'), ('Commission', 'Commission'), ('Interest', 'Interest'), ('Others', 'Others')], max_length=100),
        ),
    ]
